---
name: Send Slack Message

on:
  workflow_dispatch:

jobs:
  send-slack-message:
    runs-on: ubuntu-latest
    steps:

    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,author,action,eventName,ref,workflow,workflowRun
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
    - name: Notify Slack Custom Message
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: repo,author,action,eventName,ref,workflowRun
        custom_payload: |
          {
            attachments: [{
              "author_name": "${{ github.event.repository.name }}",
              color: 'good',
              title: 'Release Created for ${{ github.event.repository.name }}',
              changes: 'Succeeded',
              fields: [{
                title: 'Status',
                value: '${{ job.status }}',
                short: true
              },
              {
                title: 'author',
                value: '${process.env.AS_AUTHOR}',
                short: true
              },
              {
                title: 'pipeline',
                value: '${process.env.AS_WORKFLOW_RUN}',
                short: true
              },
              {
                title: 'Release URL',
                value: 'https://github.com/kahootali/golang-sample-app/releases/tag/v1.2.20',
                short: false
              },
              {
                title: 'Release Changes',
                value: 'Release for the 7th batch of DevOps class',
                short: false
              }],
              actions: [{
              }]
            }]
          }
          {
            attachments: [{
              color: 'good',
              title: 'Release Created for ${{ github.event.repository.name }}',
              text: 'release is done',
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
