name: 'CI'
on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        id: 'github_release'
        uses: ncipollo/release-action@v1.13.0
        with:
          tag: ${{ steps.changelog.outputs.toTag }}
          name: ${{ steps.changelog.outputs.toTag }}
          body: ${{ steps.changelog.outputs.changelog }}