name: 'CI'
on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify Slack of a Tag
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              attachments: [{
                "author_name": "${{ github.event.repository.name }}",
                color: 'good',
                title: 'Release Created for ${{ github.event.repository.name }}',
                changes: 'Succeeded',
                fields: [{
                  title: 'Status',
                  value: '${{ job.status }}',
                  short: true
                },
                {
                  title: 'Release Changes',
                  value: '${{ steps.changelog.outputs.changelog }}',
                  short: false
                }],
                actions: [{
                }]
              }]
            }

      - name: Create a GitHub release
        id: 'github_release'
        uses: ncipollo/release-action@v1.13.0
        with:
          tag: ${{ steps.changelog.outputs.toTag }}
          name: ${{ steps.changelog.outputs.toTag }}
          body: ${{ steps.changelog.outputs.changelog }}